import type { ItemGaleria } from "./types";

/** Conteúdo fictício de demonstração — collection `galeria` do Strapi. */

export const CATEGORIAS_GALERIA: ItemGaleria["categoria"][] = [
  "Eventos",
  "Missões",
  "Departamentos",
  "Histórico",
  "Igrejas",
];

export const GALERIA: ItemGaleria[] = [
  {
    id: "g01",
    titulo: "Culto de abertura da Convenção Nacional",
    categoria: "Eventos",
    tipo: "foto",
    data: "2025-10-15",
    local: "Natal, RN",
    imagem: { src: "/img/galeria/convencao-abertura.svg", alt: "Templo lotado durante o culto de abertura da Convenção" },
  },
  {
    id: "g02",
    titulo: "Festival de Louvor do Congresso de Jovens",
    categoria: "Eventos",
    tipo: "video",
    data: "2025-08-22",
    local: "Fortaleza, CE",
    imagem: { src: "/img/galeria/festival-louvor.svg", alt: "Ministério de louvor no palco do festival" },
  },
  {
    id: "g03",
    titulo: "Barco Missionária Ethel Matson no Rio Negro",
    categoria: "Missões",
    tipo: "foto",
    data: "2026-06-11",
    local: "Novo Airão, AM",
    imagem: { src: "/img/galeria/barco-rio-negro.svg", alt: "Barco missionário navegando ao amanhecer" },
  },
  {
    id: "g04",
    titulo: "Batismo em comunidade ribeirinha",
    categoria: "Missões",
    tipo: "foto",
    data: "2026-06-14",
    local: "Rio Negro, AM",
    imagem: { src: "/img/galeria/batismo-ribeirinho.svg", alt: "Batismo nas águas do rio ao entardecer" },
  },
  {
    id: "g05",
    titulo: "Formatura do instituto bíblico em Luanda",
    categoria: "Missões",
    tipo: "foto",
    data: "2025-12-06",
    local: "Luanda, Angola",
    imagem: { src: "/img/galeria/formatura-luanda.svg", alt: "Formandos do instituto bíblico em Luanda" },
  },
  {
    id: "g06",
    titulo: "Círculo de oração do Departamento de Mulheres",
    categoria: "Departamentos",
    tipo: "foto",
    data: "2026-03-08",
    local: "Recife, PE",
    imagem: { src: "/img/galeria/circulo-oracao.svg", alt: "Mulheres reunidas em círculo de oração" },
  },
  {
    id: "g07",
    titulo: "Férias com Cristo — Departamento de Crianças",
    categoria: "Departamentos",
    tipo: "foto",
    data: "2026-01-22",
    local: "Salvador, BA",
    imagem: { src: "/img/galeria/ferias-com-cristo.svg", alt: "Crianças em atividade recreativa e bíblica" },
  },
  {
    id: "g08",
    titulo: "Mutirão de serviço do Departamento de Homens",
    categoria: "Departamentos",
    tipo: "foto",
    data: "2025-11-09",
    local: "Mossoró, RN",
    imagem: { src: "/img/galeria/mutirao-homens.svg", alt: "Homens trabalhando na reforma de um templo" },
  },
  {
    id: "g09",
    titulo: "Primeiro templo da Missão em Manaus",
    categoria: "Histórico",
    tipo: "foto",
    data: "1941-01-01",
    local: "Manaus, AM",
    imagem: { src: "/img/galeria/primeiro-templo.svg", alt: "Fotografia histórica do primeiro templo em Manaus" },
  },
  {
    id: "g10",
    titulo: "Casal missionário Harland e Hazel Graham",
    categoria: "Histórico",
    tipo: "foto",
    data: "1939-01-01",
    local: "Manaus, AM",
    imagem: { src: "/img/galeria/casal-graham.svg", alt: "Retrato histórico do casal missionário Graham" },
  },
  {
    id: "g11",
    titulo: "Primeira Convenção Nacional",
    categoria: "Histórico",
    tipo: "foto",
    data: "1966-01-01",
    local: "Natal, RN",
    imagem: { src: "/img/galeria/primeira-convencao.svg", alt: "Fotografia histórica da primeira Convenção Nacional" },
  },
  {
    id: "g12",
    titulo: "Templo Central de Natal — Sede Nacional",
    categoria: "Igrejas",
    tipo: "foto",
    data: "2026-02-18",
    local: "Natal, RN",
    imagem: { src: "/img/galeria/templo-central.svg", alt: "Fachada do Templo Central em Natal" },
  },
  {
    id: "g13",
    titulo: "Inauguração da igreja de Belo Horizonte",
    categoria: "Igrejas",
    tipo: "video",
    data: "2026-05-30",
    local: "Belo Horizonte, MG",
    imagem: { src: "/img/galeria/inauguracao-bh.svg", alt: "Culto de inauguração da igreja de Belo Horizonte" },
  },
  {
    id: "g14",
    titulo: "Igreja MEPB de Boa Vista",
    categoria: "Igrejas",
    tipo: "foto",
    data: "2026-04-03",
    local: "Boa Vista, RR",
    imagem: { src: "/img/galeria/igreja-boavista.svg", alt: "Fachada da igreja de Boa Vista" },
  },
  {
    id: "g15",
    titulo: "Encontro Nacional de Casais",
    categoria: "Eventos",
    tipo: "foto",
    data: "2026-04-05",
    local: "João Pessoa, PB",
    imagem: { src: "/img/galeria/encontro-casais.svg", alt: "Casais reunidos durante o encontro nacional" },
  },
  {
    id: "g16",
    titulo: "Seminário Regional de Liderança",
    categoria: "Eventos",
    tipo: "foto",
    data: "2025-08-09",
    local: "Manaus, AM",
    imagem: { src: "/img/galeria/seminario-lideranca.svg", alt: "Participantes do seminário de liderança em sala de aula" },
  },
];
