import type { Igreja, UF } from "./types";

/**
 * Dados de demonstração do Localizador de Igrejas.
 *
 * Conteúdo fictício, criado apenas para o protótipo. A estrutura reproduz
 * fielmente a collection `igreja` do Strapi — ver `docs/03-modelo-de-conteudo.md`.
 */

/** Estados com presença da MEPB — pinta o mapa do Brasil no localizador. */
export const UFS_COM_PRESENCA: UF[] = [
  "AM", "PA", "RR", "AP", "RO", "AC", "TO",
  "RN", "CE", "PB", "PE", "AL", "SE", "BA", "PI", "MA",
  "SP", "RJ", "MG", "ES",
  "DF",
];

export const NOMES_UF: Record<UF, string> = {
  AC: "Acre", AL: "Alagoas", AM: "Amazonas", AP: "Amapá", BA: "Bahia",
  CE: "Ceará", DF: "Distrito Federal", ES: "Espírito Santo", GO: "Goiás",
  MA: "Maranhão", MG: "Minas Gerais", MS: "Mato Grosso do Sul",
  MT: "Mato Grosso", PA: "Pará", PB: "Paraíba", PE: "Pernambuco",
  PI: "Piauí", PR: "Paraná", RJ: "Rio de Janeiro", RN: "Rio Grande do Norte",
  RO: "Rondônia", RR: "Roraima", RS: "Rio Grande do Sul",
  SC: "Santa Catarina", SE: "Sergipe", SP: "São Paulo", TO: "Tocantins",
};

/** Horários mais comuns na denominação — evita repetição nos registros. */
const CULTOS_PADRAO: Igreja["cultos"] = [
  { dia: "Domingo", horario: "09h00", descricao: "Escola Bíblica Dominical" },
  { dia: "Domingo", horario: "18h30", descricao: "Culto de Celebração" },
  { dia: "Quarta", horario: "19h30", descricao: "Culto de Ensino e Oração" },
  { dia: "Sexta", horario: "19h30", descricao: "Culto de Libertação" },
];

export const IGREJAS: Igreja[] = [
  {
    slug: "sede-nacional-natal-rn",
    nome: "Templo Central — Sede Nacional",
    tipo: "sede-nacional",
    cidade: "Natal",
    uf: "RN",
    bairro: "Tirol",
    endereco: "Av. Prudente de Morais, 1450",
    cep: "59020-400",
    telefone: "(84) 3221-0000",
    whatsapp: "5584988000000",
    email: "sede@mepb.org.br",
    instagram: "mepbnacional",
    coordenadas: { lat: -5.7945, lng: -35.211 },
    pastor: {
      nome: "Pr. Josué Andrade Lima",
      desde: 2016,
      bio: "Pastor presidente da Sede Nacional e membro do Supremo Concílio. Formado pelo Seminário Teológico Harland Graham, dedica-se há mais de trinta anos ao ensino da Palavra e à formação de novos obreiros.",
      foto: { src: "/img/pastores/josue-lima.svg", alt: "Retrato do Pr. Josué Andrade Lima" },
    },
    cultos: [
      { dia: "Domingo", horario: "09h00", descricao: "Escola Bíblica Dominical" },
      { dia: "Domingo", horario: "18h00", descricao: "Culto de Celebração" },
      { dia: "Terça", horario: "19h30", descricao: "Culto de Oração" },
      { dia: "Quinta", horario: "19h30", descricao: "Culto de Ensino" },
      { dia: "Sábado", horario: "16h00", descricao: "Encontro de Jovens" },
    ],
    descricao:
      "Sede nacional da Missão Evangélica Pentecostal do Brasil, o Templo Central de Natal abriga a administração da denominação e recebe as Convenções Nacionais. É também a igreja onde funcionam a secretaria geral e o arquivo histórico da Missão.",
    fundacao: 1943,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Missões", "Educação", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/natal-1.svg", alt: "Fachada do Templo Central em Natal" },
      { src: "/img/igrejas/natal-2.svg", alt: "Nave principal do Templo Central durante o culto" },
      { src: "/img/igrejas/natal-3.svg", alt: "Entrada lateral e jardim do Templo Central" },
    ],
  },
  {
    slug: "primeira-igreja-manaus-am",
    nome: "Primeira Igreja MEPB de Manaus",
    tipo: "sede-estadual",
    cidade: "Manaus",
    uf: "AM",
    bairro: "Centro",
    endereco: "Rua Ramos Ferreira, 890",
    cep: "69010-120",
    telefone: "(92) 3234-0000",
    whatsapp: "5592988110000",
    email: "manaus@mepb.org.br",
    instagram: "mepbmanaus",
    coordenadas: { lat: -3.1316, lng: -60.0231 },
    pastor: {
      nome: "Pr. Elias Ferreira do Nascimento",
      desde: 2011,
      bio: "Natural do interior do Amazonas, coordena o trabalho ribeirinho no Rio Negro e supervisiona as congregações do estado.",
      foto: { src: "/img/pastores/elias-nascimento.svg", alt: "Retrato do Pr. Elias Ferreira do Nascimento" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja mãe da denominação. Foi em Manaus que o casal missionário Harland e Hazel Graham iniciou o trabalho em 1939, dando origem a toda a obra da MEPB no Brasil. Mantém até hoje o ministério de evangelismo fluvial junto às comunidades ribeirinhas.",
    fundacao: 1939,
    departamentos: ["Homens", "Mulheres", "Jovens", "Crianças", "Louvor", "Missões", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/manaus-1.svg", alt: "Fachada da Primeira Igreja MEPB de Manaus" },
      { src: "/img/igrejas/manaus-2.svg", alt: "Barco missionário atracado no Rio Negro" },
    ],
  },
  {
    slug: "igreja-central-fortaleza-ce",
    nome: "Igreja MEPB Central de Fortaleza",
    tipo: "sede-estadual",
    cidade: "Fortaleza",
    uf: "CE",
    bairro: "Aldeota",
    endereco: "Av. Santos Dumont, 2200",
    cep: "60150-161",
    telefone: "(85) 3261-0000",
    whatsapp: "5585988220000",
    email: "fortaleza@mepb.org.br",
    instagram: "mepbfortaleza",
    coordenadas: { lat: -3.7327, lng: -38.5267 },
    pastor: {
      nome: "Pr. Marcos Vinícius Teixeira",
      desde: 2018,
      bio: "Professor do Seminário Teológico Pentecostal do Ceará e responsável pela formação teológica na região Nordeste.",
      foto: { src: "/img/pastores/marcos-teixeira.svg", alt: "Retrato do Pr. Marcos Vinícius Teixeira" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Sede estadual do Ceará e casa do Seminário Teológico Pentecostal do Ceará. Reúne cerca de mil membros e coordena vinte e três congregações no estado.",
    fundacao: 1958,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Educação"],
    fotos: [
      { src: "/img/igrejas/fortaleza-1.svg", alt: "Fachada da Igreja MEPB Central de Fortaleza" },
      { src: "/img/igrejas/fortaleza-2.svg", alt: "Sala de aula do Seminário Teológico Pentecostal do Ceará" },
    ],
  },
  {
    slug: "igreja-mepb-recife-pe",
    nome: "Igreja MEPB de Recife",
    tipo: "sede-estadual",
    cidade: "Recife",
    uf: "PE",
    bairro: "Boa Vista",
    endereco: "Rua do Hospício, 415",
    cep: "50050-050",
    telefone: "(81) 3421-0000",
    whatsapp: "5581988330000",
    email: "recife@mepb.org.br",
    instagram: "mepbrecife",
    coordenadas: { lat: -8.0578, lng: -34.8829 },
    pastor: {
      nome: "Pr. Antônio Carlos Beserra",
      desde: 2009,
      bio: "Pastor há mais de trinta anos, participou da comissão de revisão do Regimento Interno da denominação.",
      foto: { src: "/img/pastores/antonio-beserra.svg", alt: "Retrato do Pr. Antônio Carlos Beserra" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Recife sediou a primeira Sede Nacional da MEPB, estabelecida em 1965, antes da transferência para Natal. A igreja preserva parte do acervo documental daquele período.",
    fundacao: 1951,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Missões"],
    fotos: [
      { src: "/img/igrejas/recife-1.svg", alt: "Fachada da Igreja MEPB de Recife" },
    ],
  },
  {
    slug: "igreja-mepb-belem-pa",
    nome: "Igreja MEPB de Belém",
    tipo: "sede-estadual",
    cidade: "Belém",
    uf: "PA",
    bairro: "Nazaré",
    endereco: "Av. Governador José Malcher, 1180",
    cep: "66055-260",
    telefone: "(91) 3241-0000",
    whatsapp: "5591988440000",
    email: "belem@mepb.org.br",
    instagram: "mepbbelem",
    coordenadas: { lat: -1.4525, lng: -48.4839 },
    pastor: {
      nome: "Pr. Raimundo Sena Barbosa",
      desde: 2014,
      bio: "Coordena o trabalho da MEPB no Marajó e a capacitação de obreiros do interior do Pará.",
      foto: { src: "/img/pastores/raimundo-barbosa.svg", alt: "Retrato do Pr. Raimundo Sena Barbosa" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Referência da denominação na região Norte, com forte atuação em projetos sociais e no atendimento às comunidades do arquipélago do Marajó.",
    fundacao: 1962,
    departamentos: ["Homens", "Mulheres", "Jovens", "Crianças", "Louvor", "Missões", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/belem-1.svg", alt: "Fachada da Igreja MEPB de Belém" },
    ],
  },
  {
    slug: "igreja-mepb-sao-paulo-sp",
    nome: "Igreja MEPB de São Paulo",
    tipo: "sede-estadual",
    cidade: "São Paulo",
    uf: "SP",
    bairro: "Tatuapé",
    endereco: "Rua Serra de Bragança, 1220",
    cep: "03318-000",
    telefone: "(11) 2295-0000",
    whatsapp: "5511988550000",
    email: "saopaulo@mepb.org.br",
    instagram: "mepbsaopaulo",
    coordenadas: { lat: -23.5405, lng: -46.5762 },
    pastor: {
      nome: "Pr. Daniel Rocha Monteiro",
      desde: 2020,
      bio: "Atua na articulação da MEPB com igrejas do Sudeste e no ministério de acolhimento a migrantes nordestinos na capital paulista.",
      foto: { src: "/img/pastores/daniel-monteiro.svg", alt: "Retrato do Pr. Daniel Rocha Monteiro" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Fundada por famílias nordestinas migrantes, a igreja mantém um dos mais ativos ministérios de acolhimento da denominação e reúne membros de doze estados diferentes.",
    fundacao: 1978,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Educação"],
    fotos: [
      { src: "/img/igrejas/saopaulo-1.svg", alt: "Fachada da Igreja MEPB de São Paulo" },
    ],
  },
  {
    slug: "igreja-mepb-rio-de-janeiro-rj",
    nome: "Igreja MEPB do Rio de Janeiro",
    tipo: "igreja",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    bairro: "Tijuca",
    endereco: "Rua Conde de Bonfim, 780",
    cep: "20530-002",
    telefone: "(21) 2568-0000",
    whatsapp: "5521988660000",
    email: "riodejaneiro@mepb.org.br",
    instagram: "mepbrio",
    coordenadas: { lat: -22.9243, lng: -43.2372 },
    pastor: {
      nome: "Pr. Sérgio Vasconcelos Pinto",
      desde: 2017,
      bio: "Dedica-se ao ministério com famílias e à formação de líderes de pequenos grupos.",
      foto: { src: "/img/pastores/sergio-pinto.svg", alt: "Retrato do Pr. Sérgio Vasconcelos Pinto" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja urbana com forte trabalho junto a famílias e adolescentes, mantém projeto de reforço escolar aberto à comunidade da região da Tijuca.",
    fundacao: 1984,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor"],
    fotos: [
      { src: "/img/igrejas/rio-1.svg", alt: "Fachada da Igreja MEPB do Rio de Janeiro" },
    ],
  },
  {
    slug: "igreja-mepb-salvador-ba",
    nome: "Igreja MEPB de Salvador",
    tipo: "sede-estadual",
    cidade: "Salvador",
    uf: "BA",
    bairro: "Rio Vermelho",
    endereco: "Rua Guedes Cabral, 340",
    cep: "41940-450",
    telefone: "(71) 3334-0000",
    whatsapp: "5571988770000",
    email: "salvador@mepb.org.br",
    instagram: "mepbsalvador",
    coordenadas: { lat: -13.0102, lng: -38.4914 },
    pastor: {
      nome: "Pr. Gilberto Almeida Santos",
      desde: 2013,
      bio: "Supervisiona dezoito congregações na Bahia e coordena o Congresso Regional Nordeste.",
      foto: { src: "/img/pastores/gilberto-santos.svg", alt: "Retrato do Pr. Gilberto Almeida Santos" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Sede estadual da Bahia, conhecida pelo ministério de louvor e pelo trabalho de assistência social no bairro do Rio Vermelho.",
    fundacao: 1969,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/salvador-1.svg", alt: "Fachada da Igreja MEPB de Salvador" },
    ],
  },
  {
    slug: "igreja-mepb-joao-pessoa-pb",
    nome: "Igreja MEPB de João Pessoa",
    tipo: "sede-estadual",
    cidade: "João Pessoa",
    uf: "PB",
    bairro: "Manaíra",
    endereco: "Av. Governador Flávio Ribeiro Coutinho, 640",
    cep: "58037-000",
    telefone: "(83) 3226-0000",
    whatsapp: "5583988880000",
    email: "joaopessoa@mepb.org.br",
    instagram: "mepbjoaopessoa",
    coordenadas: { lat: -7.1045, lng: -34.8362 },
    pastor: {
      nome: "Pr. Fábio Henrique Cavalcanti",
      desde: 2019,
      bio: "Trabalha na integração dos departamentos estaduais e no discipulado de novos convertidos.",
      foto: { src: "/img/pastores/fabio-cavalcanti.svg", alt: "Retrato do Pr. Fábio Henrique Cavalcanti" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja em crescimento na capital paraibana, com destaque para o ministério de adolescentes e o projeto de esporte comunitário.",
    fundacao: 1972,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor"],
    fotos: [
      { src: "/img/igrejas/joaopessoa-1.svg", alt: "Fachada da Igreja MEPB de João Pessoa" },
    ],
  },
  {
    slug: "igreja-mepb-mossoro-rn",
    nome: "Igreja MEPB de Mossoró",
    tipo: "igreja",
    cidade: "Mossoró",
    uf: "RN",
    bairro: "Centro",
    endereco: "Rua Cel. Gurgel, 215",
    cep: "59600-000",
    telefone: "(84) 3315-0000",
    whatsapp: "5584988990000",
    email: "mossoro@mepb.org.br",
    coordenadas: { lat: -5.1875, lng: -37.3441 },
    pastor: {
      nome: "Pr. Jonas Batista de Oliveira",
      desde: 2015,
      bio: "Pastoreia a igreja e coordena o trabalho de evangelismo no interior potiguar.",
      foto: { src: "/img/pastores/jonas-oliveira.svg", alt: "Retrato do Pr. Jonas Batista de Oliveira" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Segunda maior igreja da MEPB no Rio Grande do Norte, atende o oeste potiguar e mantém quatro congregações no semiárido.",
    fundacao: 1966,
    departamentos: ["Homens", "Mulheres", "Jovens", "Crianças", "Louvor", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/mossoro-1.svg", alt: "Fachada da Igreja MEPB de Mossoró" },
    ],
  },
  {
    slug: "igreja-mepb-parnamirim-rn",
    nome: "Igreja MEPB de Parnamirim",
    tipo: "igreja",
    cidade: "Parnamirim",
    uf: "RN",
    bairro: "Nova Parnamirim",
    endereco: "Av. Ayrton Senna, 3120",
    cep: "59151-600",
    telefone: "(84) 3272-0000",
    whatsapp: "5584987110000",
    email: "parnamirim@mepb.org.br",
    coordenadas: { lat: -5.9156, lng: -35.2628 },
    pastor: {
      nome: "Pr. Wellington Souza Dantas",
      desde: 2021,
      bio: "Lidera o projeto de plantação de igrejas na região metropolitana de Natal.",
      foto: { src: "/img/pastores/wellington-dantas.svg", alt: "Retrato do Pr. Wellington Souza Dantas" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja jovem e em expansão na região metropolitana de Natal, referência no trabalho com crianças e no ministério de casais.",
    fundacao: 2004,
    departamentos: ["Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor"],
    fotos: [
      { src: "/img/igrejas/parnamirim-1.svg", alt: "Fachada da Igreja MEPB de Parnamirim" },
    ],
  },
  {
    slug: "igreja-mepb-teresina-pi",
    nome: "Igreja MEPB de Teresina",
    tipo: "sede-estadual",
    cidade: "Teresina",
    uf: "PI",
    bairro: "Jóquei",
    endereco: "Av. Homero Castelo Branco, 980",
    cep: "64048-000",
    telefone: "(86) 3233-0000",
    whatsapp: "5586987220000",
    email: "teresina@mepb.org.br",
    coordenadas: { lat: -5.0892, lng: -42.8016 },
    pastor: {
      nome: "Pr. Aldenir Moura Campelo",
      desde: 2012,
      bio: "Responsável pela expansão da denominação no Piauí e pelo programa de rádio semanal da MEPB no estado.",
      foto: { src: "/img/pastores/aldenir-campelo.svg", alt: "Retrato do Pr. Aldenir Moura Campelo" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Sede estadual do Piauí, mantém programa de rádio semanal e um centro de apoio a famílias em situação de vulnerabilidade.",
    fundacao: 1974,
    departamentos: ["Homens", "Mulheres", "Jovens", "Crianças", "Louvor", "Educação"],
    fotos: [
      { src: "/img/igrejas/teresina-1.svg", alt: "Fachada da Igreja MEPB de Teresina" },
    ],
  },
  {
    slug: "igreja-mepb-sao-luis-ma",
    nome: "Igreja MEPB de São Luís",
    tipo: "igreja",
    cidade: "São Luís",
    uf: "MA",
    bairro: "Cohama",
    endereco: "Av. Daniel de La Touche, 1450",
    cep: "65074-115",
    telefone: "(98) 3245-0000",
    whatsapp: "5598987330000",
    email: "saoluis@mepb.org.br",
    coordenadas: { lat: -2.5307, lng: -44.2989 },
    pastor: {
      nome: "Pr. Cleiton Ribeiro Mendes",
      desde: 2018,
      bio: "Atua no discipulado de jovens universitários e na capacitação de líderes de louvor.",
      foto: { src: "/img/pastores/cleiton-mendes.svg", alt: "Retrato do Pr. Cleiton Ribeiro Mendes" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja com forte presença universitária, mantém núcleo de estudos bíblicos em três campi da capital maranhense.",
    fundacao: 1989,
    departamentos: ["Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/saoluis-1.svg", alt: "Fachada da Igreja MEPB de São Luís" },
    ],
  },
  {
    slug: "igreja-mepb-maceio-al",
    nome: "Igreja MEPB de Maceió",
    tipo: "igreja",
    cidade: "Maceió",
    uf: "AL",
    bairro: "Farol",
    endereco: "Av. Fernandes Lima, 2340",
    cep: "57055-000",
    telefone: "(82) 3221-0000",
    whatsapp: "5582987440000",
    email: "maceio@mepb.org.br",
    coordenadas: { lat: -9.6498, lng: -35.7089 },
    pastor: {
      nome: "Pr. Ivanildo Pereira da Silva",
      desde: 2016,
      bio: "Coordena o trabalho de assistência social da MEPB em Alagoas.",
      foto: { src: "/img/pastores/ivanildo-silva.svg", alt: "Retrato do Pr. Ivanildo Pereira da Silva" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Conhecida pelo projeto de distribuição de alimentos e pelo atendimento a pessoas em situação de rua no centro de Maceió.",
    fundacao: 1981,
    departamentos: ["Homens", "Mulheres", "Jovens", "Crianças", "Louvor"],
    fotos: [
      { src: "/img/igrejas/maceio-1.svg", alt: "Fachada da Igreja MEPB de Maceió" },
    ],
  },
  {
    slug: "igreja-mepb-brasilia-df",
    nome: "Igreja MEPB de Brasília",
    tipo: "igreja",
    cidade: "Brasília",
    uf: "DF",
    bairro: "Taguatinga",
    endereco: "QNL 12, Conjunto D, Lote 5",
    cep: "72151-540",
    telefone: "(61) 3352-0000",
    whatsapp: "5561987550000",
    email: "brasilia@mepb.org.br",
    coordenadas: { lat: -15.8339, lng: -48.0578 },
    pastor: {
      nome: "Pr. Reginaldo Alves Braga",
      desde: 2020,
      bio: "Representa a MEPB junto a órgãos e entidades interdenominacionais na capital federal.",
      foto: { src: "/img/pastores/reginaldo-braga.svg", alt: "Retrato do Pr. Reginaldo Alves Braga" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja da capital federal, responsável pela representação institucional da denominação junto a entidades nacionais.",
    fundacao: 1993,
    departamentos: ["Homens", "Mulheres", "Jovens", "Adolescentes", "Crianças", "Louvor"],
    fotos: [
      { src: "/img/igrejas/brasilia-1.svg", alt: "Fachada da Igreja MEPB de Brasília" },
    ],
  },
  {
    slug: "congregacao-rio-negro-am",
    nome: "Congregação Ribeirinha do Rio Negro",
    tipo: "congregacao",
    cidade: "Novo Airão",
    uf: "AM",
    bairro: "Comunidade São Sebastião",
    endereco: "Margem esquerda do Rio Negro, km 42",
    cep: "69730-000",
    whatsapp: "5592987660000",
    email: "ribeirinho@mepb.org.br",
    coordenadas: { lat: -2.6297, lng: -60.9436 },
    pastor: {
      nome: "Missionário Paulo Tavares",
      desde: 2010,
      bio: "Conduz o barco Missionária Ethel Matson e atende dezenove comunidades ao longo do Rio Negro.",
      foto: { src: "/img/pastores/paulo-tavares.svg", alt: "Retrato do missionário Paulo Tavares" },
    },
    cultos: [
      { dia: "Sábado", horario: "18h00", descricao: "Culto de Celebração" },
      { dia: "Domingo", horario: "09h00", descricao: "Escola Bíblica e visita às comunidades" },
    ],
    descricao:
      "Ponto de apoio do ministério fluvial da MEPB. A partir daqui, o barco Missionária Ethel Matson leva assistência espiritual, atendimento de saúde e material escolar a comunidades ribeirinhas de difícil acesso.",
    fundacao: 1998,
    departamentos: ["Crianças", "Missões", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/rionegro-1.svg", alt: "Congregação ribeirinha às margens do Rio Negro" },
      { src: "/img/igrejas/rionegro-2.svg", alt: "Barco Missionária Ethel Matson em atendimento" },
    ],
  },
  {
    slug: "igreja-mepb-boa-vista-rr",
    nome: "Igreja MEPB de Boa Vista",
    tipo: "igreja",
    cidade: "Boa Vista",
    uf: "RR",
    bairro: "Centro",
    endereco: "Av. Ville Roy, 5200",
    cep: "69301-000",
    telefone: "(95) 3224-0000",
    whatsapp: "5595987770000",
    email: "boavista@mepb.org.br",
    coordenadas: { lat: 2.8235, lng: -60.6758 },
    pastor: {
      nome: "Pr. Hélio Marques Fontes",
      desde: 2019,
      bio: "Atua no acolhimento de imigrantes venezuelanos e no ministério indígena em Roraima.",
      foto: { src: "/img/pastores/helio-fontes.svg", alt: "Retrato do Pr. Hélio Marques Fontes" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Fronteira missionária da denominação, com trabalho de acolhimento a imigrantes e cultos realizados em português e espanhol.",
    fundacao: 2001,
    departamentos: ["Mulheres", "Jovens", "Crianças", "Missões", "Evangelismo"],
    fotos: [
      { src: "/img/igrejas/boavista-1.svg", alt: "Fachada da Igreja MEPB de Boa Vista" },
    ],
  },
  {
    slug: "igreja-mepb-belo-horizonte-mg",
    nome: "Igreja MEPB de Belo Horizonte",
    tipo: "igreja",
    cidade: "Belo Horizonte",
    uf: "MG",
    bairro: "Santa Efigênia",
    endereco: "Rua Domingos Vieira, 590",
    cep: "30150-240",
    telefone: "(31) 3241-0000",
    whatsapp: "5531987880000",
    email: "bh@mepb.org.br",
    coordenadas: { lat: -19.9245, lng: -43.9276 },
    pastor: {
      nome: "Pr. Emerson Lopes Ferreira",
      desde: 2022,
      bio: "Lidera o núcleo de plantação de igrejas da MEPB no Sudeste.",
      foto: { src: "/img/pastores/emerson-ferreira.svg", alt: "Retrato do Pr. Emerson Lopes Ferreira" },
    },
    cultos: CULTOS_PADRAO,
    descricao:
      "Igreja mais recente da denominação no Sudeste, funciona também como base do programa de plantação de igrejas na região.",
    fundacao: 2015,
    departamentos: ["Jovens", "Adolescentes", "Crianças", "Louvor", "Missões"],
    fotos: [
      { src: "/img/igrejas/bh-1.svg", alt: "Fachada da Igreja MEPB de Belo Horizonte" },
    ],
  },
];

/** Estados que aparecem no filtro, ordenados pelo nome. */
export const UFS_DISPONIVEIS = Array.from(new Set(IGREJAS.map((i) => i.uf))).sort(
  (a, b) => NOMES_UF[a].localeCompare(NOMES_UF[b], "pt-BR"),
);

/** Cidades de um estado, ordenadas. Usado no filtro dependente do localizador. */
export function cidadesPorUF(uf: UF): string[] {
  return Array.from(
    new Set(IGREJAS.filter((i) => i.uf === uf).map((i) => i.cidade)),
  ).sort((a, b) => a.localeCompare(b, "pt-BR"));
}

export function getIgreja(slug: string): Igreja | undefined {
  return IGREJAS.find((i) => i.slug === slug);
}
